### ISSUE TITLE
Help: Sorry, but I could not load the Header component on the host container

### ISSUE THREAD

**Issue by JoseJesusOchoaTorres** [harshpatel1408/NextJS_microfrontend#2]
Hello there I hope you can help me; I wanted to run the project but I am getting an error, when you are running it on your local are you getting the same error message?

![imagen](https://user-images.githubusercontent.com/8441759/188054308-76ff0cc7-afad-4f62-919c-5965856c3cfa.png)

Note: As you can see I am running the Header component on port 3000 and the consumer host app on 3002.

Thanks in advance.

**Comment by JoseJesusOchoaTorres** [comment]
Update: After using Suspense it started showing a different error message.

![imagen](https://user-images.githubusercontent.com/8441759/188061079-789fe72e-05dd-4f53-bc8d-a0129fdb92a8.png)

**Comment by harshpatel1408** [comment]
can you see the built content on hosted file? visit the [URL](http:localhost:8888/remoteEntry.js) written in `next.config.js`
