### ISSUE TITLE
Code not working.

### ISSUE THREAD

**Issue by rmarku** [harshpatel1408/NextJS_microfrontend#3]
The code as is in the repo is not working. Follow the steps on the main readme and it doesn't work. Here is a video of the steps.

https://user-images.githubusercontent.com/1113370/188334644-92682792-efe8-4429-be9d-c6517a035974.mp4

**Comment by rmarku** [comment]
Added PR #4 to fix the name of the imported fe2 app. It still doesn't work.

If I enter http://localhost:8888/remoteEntry.js or http://localhost:8889/remoteEntry2.js, I get a 404 on the browser, so it looks like fe1 and fe2 are not exporting their modules.

Can you please upload the working and tested code? Clearer steps on the README.md to reproduce if we (as all that replies to the blog comments) can't have working code from the blog publication.

**Comment by ImBIOS** [comment]
the weird this is this project contains package-lock.json by npm, but the README.md guide us to use yarn.

**Comment by harshpatel1408** [comment]
Hey @rmarku 

I have updated the `README` and code. Let's see if you can run it or not. Attached working video for reference. 

Actually, I forgot to commit the updated import but anyway thanks for the attention. I have fixed the import as you suggested in [PR](https://github.com/harshpatel1408/NextJS_microfrontend/pull/4). 

https://user-images.githubusercontent.com/11008243/188813564-3683a12b-e23c-4b52-89d5-b141edeeb5a4.mp4

**Comment by harshpatel1408** [comment]
@ImBIOS previously used `npm` to handle operations that's why `package-lock.json` were there.

**Comment by JoseJesusOchoaTorres** [comment]
@harshpatel1408 Hey, how are you running the remoteEntry.js on the 8888 port?

`fe1: "fe1@http://localhost:8888/remoteEntry.js",`

You run the fe1 with `yarn start` in the above video on the 3000 port.

**Comment by burhanNeosoft** [comment]
@harshpatel1408 I'm trying this url http://localhost:8888/remoteEntry.js but getting 404. I'm doing this setup in ubuntu, Please suggest me how can i access remoteEntry.js file
